version: 2.1

jobs:
  cleanup:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - todocoop-{{checksum "yarn.lock"}}
      - run:
          name: install packages
          command: yarn install --frozen-lockfile
      - save_cache:
          key: todocoop-{{checksum "yarn.lock"}}
          paths:
            - ~/.yarn
      - run:
          name: delete stale rooms
          command: yarn cleanup

workflows:
  nightly:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - main
    jobs:
      - cleanup

  cleanup:
    jobs:
      - cleanup:
          filters:
            branches:
              only:
                - main
